BotToken: ''
TimerTime: 900 #in seconds
CommandExecutedOnTimerEnd: ''
CommandExecutedOnEventStart: 'say start'
StartMessage: 'ยง6The event has started! Good luck.'
StopMessage: 'ยง6The event is over!'
TimeBeforeEventStart: 15 #in seconds
MessageOnTimerStart: ''
WorldName: 'test'
LogWorldChanges: false
WebhookURL: '' #Go to channel settings -> Integrations -> Webhooks -> New Webhook and paste url in the two ''
MessageChannel: '846779760713793558'
CommandExecutedOnJoinQuit: ''
CommandExecutedOnPlayerDeath: ''
DutyOnCommand: ''
DutyOffCommand: ''
ModRoleId: 858483265475837972
BotPrefix: 'v!'
death-message-channel-id: